development:
  adapter: mysql2
  encoding: utf8
  database: bcw-ng_development
  pool: 5
  username: root
  password: rootpass
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: bcw-ng_test
  pool: 5
  username: root
  password: rootpass
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  database: bcw-ng_production
  pool: 5
  username: root
  password: rootpass
  socket: /tmp/mysql.sock
